when:
  event:
    - push
    - pull_request
    - manual

steps:
  test:
    image: golang:1.25.1
    commands:
      - go mod download
      - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
      - go vet ./...
      - go build -o or-analytics .

  upload-to-s3:
    image: woodpeckerci/plugin-s3
    settings:
      bucket:
        from_secret: s3_bucket
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      region:
        from_secret: s3_region
      endpoint:
        from_secret: s3_endpoint
      path_style: true
      source: or-analytics
      target: /builds/${CI_COMMIT_SHA}/or-analytics
    when:
      event:
        - push
      branch:
        - main

  discord-notification:
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      username: Woodpecker CI
    failure: ignore
