when:
  event:
    - push
    - pull_request
    - manual

steps:
  test:
    image: golang:1.25.1
    commands:
      - go mod download
      - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
      - go vet ./...
      - go build -o or-analytics .

  discord-notification:
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      username: Woodpecker CI
    failure: ignore
